### ISSUE TITLE
希望作者优化下数据库的连接

### ISSUE THREAD

**Issue by ChromiumX** [glzjin/ssshell-jar#14]
24个服务器就使得连接数量达到低配RDS的封顶，我并不懂代码，完全是个外行，只会安装教程使用，每周日我会定时捐赠10%的，不过不是商业站，只被动推广，所以金额不会多，不要介意，全当是一点心意。

**Comment by glzjin** [comment]
没事，大家都不容易，还是你自己留着吧。好的=、=下个版本加个连接数设置吧。=、=不贵最好的还是自己用服务器搭个MySQL，免得一些你懂的原因。
glzjin
2016年5月12日 下午7:19，ChromiumX <notifications@github.com>写道：24个服务器就使得连接数量达到低配RDS的封顶，我并不懂代码，完全是个外行，只会安装教程使用，每周日我会定时捐赠10%的，不过不是商业站，只被动推广，所以金额不会多，不要介意，全当是一点心意。

**Comment by ChromiumX** [comment]
用RDS是应为手贱，弄炸过数据库，还好那个时候人不多，手动还原数据。自从那以后就拿出预算用RDS了，数据还是很重要的，我不太放心我自建的MySQL。
