### ISSUE TITLE
1.4.10测试finalspeed.依然无法记录流量

### ISSUE THREAD

**Issue by lion1991** [glzjin/ssshell-jar#15]
使用普通方式正常记录流量.切换到finalspeel后在ss客户端上使用127.0.0.1之后连接成功可以上网.模式是udp. 服务器后端没有上传此端口号用户数据.

**Comment by glzjin** [comment]
那么没办法了 有空再看看了
glzjin
2016年5月13日 上午12:10，lion1991 <notifications@github.com>写道：使用普通方式正常记录流量.切换到finalspeel后在ss客户端上使用127.0.0.1之后连接成功可以上网.模式是udp. 服务器后端没有上传此端口号用户数据.

**Comment by glzjin** [comment]
你把设置里nic=any试试吧
glzjin
2016年5月13日 上午12:22，glzjin <glzjin@zhaojin97.cn>写道：那么没办法了 有空再看看了
glzjin
2016年5月13日 上午12:10，lion1991 <notifications@github.com>写道：使用普通方式正常记录流量.切换到finalspeel后在ss客户端上使用127.0.0.1之后连接成功可以上网.模式是udp. 服务器后端没有上传此端口号用户数据.
