### ISSUE TITLE
ssshell.jar能启动但是ss无法连接100%错误

### ISSUE THREAD

**Issue by yestop** [glzjin/ssshell-jar#20]
155版本，java 看到ssshell.jar能启动，无错误，也能add新用户，就是没法连接ss。
换成老版本147就能连ss了。。。
155和147之间就换了个conf，也就是150里面的那4句话
db_connection=4
autoexec=1
antissattack=1
httponly=0
怎么破？

**Comment by ChromiumX** [comment]
+1

**Comment by glzjin** [comment]
把 /tmp/ssshell 删除之后再运行试试

**Comment by ChromiumX** [comment]
还是不行

**Comment by glzjin** [comment]
你是不是 开了限速=、=

**Comment by glzjin** [comment]
在这个版本里移除了tc限速 改为trickle 了 所以请先安装trickle

**Comment by ChromiumX** [comment]
speedlimit=1 也受到影响么

**Comment by glzjin** [comment]
是的 如果你给用户设置的限速为非0的话也会有影响，因为删除了tc限速了。

**Comment by glzjin** [comment]
https://github.com/glzjin/ssshell-jar/issues/21

**Comment by glzjin** [comment]
wget https://github.com/glzjin/ssshell-jar/raw/master/ssshell.jar -O /root/ssshell/ssshell.jar

service supervisord restart
