### ISSUE TITLE
运行ssshell.sh报错   之前的机器都不会 新买一台KVM就报错了

### ISSUE THREAD

**Issue by nyancat1** [glzjin/ssshell-jar#25]
WARNING: cannot verify raw.githubusercontent.com?. certificate, issued by ?.C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA?.
  Issued certificate not yet valid.

**Comment by glzjin** [comment]
yum update -y
glzjin
2016年5月21日 下午1:25，nyancat1 <notifications@github.com>写道：WARNING: cannot verify raw.githubusercontent.com?. certificate, issued by ?.C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA?.
  Issued certificate not yet valid.

**Comment by nyancat1** [comment]
[root@Kvmla-201605211098 ~]# yum update -y
Loaded plugins: fastestmirror, presto
Loading mirror speeds from cached hostfile
Error: Cannot retrieve metalink for repository: epel. Please verify its path and try again

**Comment by nyancat1** [comment]
T_T

**Comment by glzjin** [comment]
自个儿想办法解决吧。。。这个系统问题我帮不了你
