### ISSUE TITLE
新版后端不统计人数和流量

### ISSUE THREAD

**Issue by david7207** [glzjin/ssshell-jar#27]
我节点参数配置好了以后，节点不统计人数还有使用的流量，一直都是0，但是我已经使用了呀！还有，我关闭了ssshell，但是节点的ss-server还在运行，用户还可以用SS上网！

**Comment by my971208** [comment]
关闭ssshell不代表关闭掉ss-server，ss-server需要手动kill

**Comment by david7207** [comment]
@my971208 这个知道了，但是为啥没法统计在线人数还有流量记录呀

**Comment by glzjin** [comment]
目测你用的是openvz而且还没配置好ipv6，请彻底地将ipv6关闭，还有，ssshell设计是一直运行的，手动关闭请自行 killall ss-server
glzjin
2016年5月22日 下午9:01，david <notifications@github.com>写道：我节点参数配置好了以后，节点不统计人数还有使用的流量，一直都是0，但是我已经使用了呀！还有，我关闭了ssshell，但是节点的ss-server还在运行，用户还可以用SS上网！

**Comment by david7207** [comment]
应该不是openvz吧，ifconfig显示的是eth0，这个没错，IPV6怎么彻底关闭？

**Comment by david7207** [comment]
我用你的v1.5.0没问题，这个版本以上的都有问题

**Comment by david7207** [comment]
现阶段IPV6已经彻底关了，但是还是效果一样，ifconfig已经看不到IPV6的本地地址了！还有，我的ifconfig出来的是eth0

**Comment by david7207** [comment]
@glzjin

**Comment by glzjin** [comment]
看看ss server的运行用户吧

**Comment by david7207** [comment]
@glzjin ssshell+这个用户
