### ISSUE TITLE
为什么流量窗中只有一个节点有统计？

### ISSUE THREAD

**Issue by daihk** [glzjin/ssshell-jar#35]
你好，在ssshell.conf 配置相同(节点IP，和nodeid不同)情况下，负载、uptime、在线人数都有统计，为什么流量窗只有一个节点有统计？

**Comment by glzjin** [comment]
=、=截图看看？

**Comment by daihk** [comment]
## 这是观察窗的截图，只有一个节点有数据：
![screenshot from 2016-07-04 08-51-16](https://cloud.githubusercontent.com/assets/17514004/16548688/3b281104-41c7-11e6-90f1-339107df4cd5.png)
## 节点列表里的统计图如下，只显示2张(有、无数据)：
1.
![screenshot from 2016-07-04 08-52-33](https://cloud.githubusercontent.com/assets/17514004/16548706/ba0729d8-41c7-11e6-882a-195176dddfe4.png)
2.
![screenshot from 2016-07-04 08-51-59](https://cloud.githubusercontent.com/assets/17514004/16548707/c193d0a2-41c7-11e6-8319-c9a5fa74ddc0.png)
