### ISSUE TITLE
执行ssshell.jar时报错

### ISSUE THREAD

**Issue by lpker** [glzjin/ssshell-jar#4]
调试时发现前端无法显示在线人数，于是执行了一下ssshell发现报错如下，用的是1.49的后端，这应该怎么解决？
![qq 20160504022412](https://cloud.githubusercontent.com/assets/19174143/14993998/1501c6e8-11a0-11e6-8a83-2621241eb106.jpg)

**Comment by glzjin** [comment]
= =你有参数没填对
