### ISSUE TITLE
无法正常使用ss

### ISSUE THREAD

**Issue by moqiaoduo** [glzjin/ssshell-jar#42]
防火墙已关，客户端用其他节点正常，客户端配置正确，服务端没有显示错误。
然而始终无法正常使用。
服务端所显示的信息：
[INFO][2016-07-10 17:46:49]Connecting to mysql....
[INFO][2016-07-10 17:46:49]Getting the OnlineUser.....
[INFO][2016-07-10 17:46:49]Sleeping...
不断的循环这些，没有其他内容，只有开头一大串东西
P.S. 我是搬瓦工的机器，他的网卡配置可能有点奇怪，但我不知道在哪里出错

**Comment by lz2xg** [comment]
一样的问题，2个节点配置完全一样，运行没有错误提示，魔改版后台节点都是绿的。但一个节点连接正常，另一个节点SS死活连接不上。iptables关闭还是不行，奇怪的是同一个服务器安装shadowsocks -rm版服务端能正常使用，用这个ssshell-jar就不行了
