### ISSUE TITLE
此版本只适合单主机吗,能否像gomu一样多个服务器的后端连接到sspanel

### ISSUE THREAD

**Issue by lion1991** [glzjin/ssshell-jar#7]
数据库的连接选项应该只能连接本地的数据库.目前有办法解决这个问题吗

**Comment by glzjin** [comment]
你自己开远程访问不就行了
glzjin
2016年5月7日 上午12:45，lion1991 <notifications@github.com>写道：数据库的连接选项应该只能连接本地的数据库.目前有办法解决这个问题吗

**Comment by j0hnnie** [comment]
--2016-05-07 10:01:20--  (try: 2)  https://www.zhaoj.in/wp-content/uploads/2016/04/1460020148ff898a7205d4a40e6665da6ef8f48850.zip
Connecting to www.zhaoj.in|43.241.50.204|:443... failed: Connection timed out.
Retrying.

一键安装失败

**Comment by lion1991** [comment]
@j0hnnie 国外的主机是无法连接的.建议你找个国内的做个跳转吧.

**Comment by glzjin** [comment]
他说的不是这个
glzjin
2016年5月7日 上午10:12，lion1991 <notifications@github.com>写道：@j0hnnie 国外的主机是无法连接的.建议你找个国内的做个跳转吧.

**Comment by lion1991** [comment]
sspanel面板的数据库已经开启远程访问了.但是java还是报错连不上.本地的倒是可以.

[root@kvmla1 ssshell]# java -jar ssshell.jar
May 06, 2016 9:43:19 PM com.mchange.v2.log.MLog
INFO: MLog clients using java 1.4+ standard logging.
May 06, 2016 9:43:20 PM com.mchange.v2.c3p0.C3P0Registry
INFO: Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
[info][2016-05-06 21:43:21]Connecting to mysql....
May 06, 2016 9:43:21 PM com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource
INFO: Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> z8kflt9g121fk3m7u4ixf|31c88ec8, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> com.mysql.jdbc.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> z8kflt9g121fk3m7u4ixf|31c88ec8, idleConnectionTestPeriod -> 0, initialPoolSize -> 3, jdbcUrl -> jdbc:mysql://45.32.83.2/sspanel?autoReconnect=true, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 120, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 10, maxStatements -> 50, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]

卡住不动了...

**Comment by lion1991** [comment]
等了大概几分钟后面显示:

May 07, 2016 10:48:37 AM com.mchange.v2.async.ThreadPoolAsynchronousRunner
WARNING: com.mchange.v2.async.ThreadPoolAsynchronousRunner$DeadlockDetector@37b05bc1 -- APPARENT DEADLOCK!!! Creating emergency threads for unassigned pending tasks!
May 07, 2016 10:48:37 AM com.mchange.v2.async.ThreadPoolAsynchronousRunner
WARNING: com.mchange.v2.async.ThreadPoolAsynchronousRunner$DeadlockDetector@37b05bc1 -- APPARENT DEADLOCK!!! Complete Status:
        Managed Threads: 3
        Active Threads: 3
        Active Tasks:
                com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@4d118be7
                        on thread: C3P0PooledConnectionPoolManager[identityToken->z8kflt9g121jjrc1he59wf|31c88ec8]-HelperThread-#1
                com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@4978e489
                        on thread: C3P0PooledConnectionPoolManager[identityToken->z8kflt9g121jjrc1he59wf|31c88ec8]-HelperThread-#0
                com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@35c988af
                        on thread: C3P0PooledConnectionPoolManager[identityToken->z8kflt9g121jjrc1he59wf|31c88ec8]-HelperThread-#2
        Pending Tasks:
                com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@18654633
                com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@59eaa86b
                com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@57b85373
Pool thread stack traces:
        Thread[C3P0PooledConnectionPoolManager[identityToken->z8kflt9g121jjrc1he59wf|31c88ec8]-HelperThread-#0,5,main]
                java.net.PlainSocketImpl.socketConnect(Native Method)
                java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
                java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
                java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
                java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
                java.net.Socket.connect(Socket.java:589)
                com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213)
                com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:297)
                com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2232)
                com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2085)
                com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2069)
                com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
                com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
                sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
                com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
                com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
                com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
                com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
                com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
                com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
                com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
                com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
                com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
                com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
                com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
        Thread[C3P0PooledConnectionPoolManager[identityToken->z8kflt9g121jjrc1he59wf|31c88ec8]-HelperThread-#1,5,main]
                java.net.PlainSocketImpl.socketConnect(Native Method)
                java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
                java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
                java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
                java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
                java.net.Socket.connect(Socket.java:589)
                com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213)
                com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:297)
                com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2232)
                com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2085)
                com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2069)
                com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
                com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
                sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
                com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
                com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
                com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
                com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
                com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
                com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
                com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
                com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
                com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
                com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
                com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
        Thread[C3P0PooledConnectionPoolManager[identityToken->z8kflt9g121jjrc1he59wf|31c88ec8]-HelperThread-#2,5,main]
                java.net.PlainSocketImpl.socketConnect(Native Method)
                java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
                java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
                java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
                java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
                java.net.Socket.connect(Socket.java:589)
                com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213)
                com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:297)
                com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2232)
                com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2085)
                com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2069)
                com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
                com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
                sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
                com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
                com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
                com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
                com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
                com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
                com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
                com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
                com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
                com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
                com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
                com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
