### ISSUE TITLE
关掉ssshell也还能用？

### ISSUE THREAD

**Issue by fakehaoyang** [glzjin/ssshell-jar#8]
现在里面几个下载文件的链接失效了诶，我用的以前的，手动上传上去的文件
我发现，即使关闭supervisord了，用户也能连接，只是面板上显示节点离线
不用supervisord的话，java -jar ssshell.jar，然后再关掉，也一样。

是不是 ssshell.jar只是来控制用户的速度，权限啥的，要关掉还得关shadowsocks-libev？

**Comment by glzjin** [comment]
是的，自己杀掉
glzjin
2016年5月7日 上午11:07，fakehaoyang <notifications@github.com>写道：现在里面几个下载文件的链接失效了诶，我用的以前的，手动上传上去的文件
我发现，即使关闭supervisord了，用户也能连接，只是面板上显示节点离线
不用supervisord的话，java -jar ssshell.jar，然后再关掉，也一样。

是不是 ssshell.jar只是来控制用户的速度，权限啥的，要关掉还得关shadowsocks-libev？
