### ISSUE TITLE
网卡绑定了2个IP的怎么破？

### ISSUE THREAD

**Issue by sgwyhwt** [glzjin/ssshell-jar#9]
想添加两个节点，分别用这两个IP
但是ssshell.conf里只能指定一个IP不是？

**Comment by glzjin** [comment]
是的，目前还没做统计两个IP的。------------------------------------------------------------------发件人：Kevin <notifications@github.com>发送时间：2016年5月10日(星期二) 23:56收件人：glzjin/ssshell-jar <ssshell-jar@noreply.github.com>主　题：[glzjin/ssshell-jar] 网卡绑定了2个IP的怎么破？ (#9)
想添加两个节点，分别用这两个IP

但是ssshell.conf里只能指定一个IP不是？—
